name: Hourly Amazon Price Bot

on:
  schedule:
    - cron: '0 * * * *'   # every hour on the hour
  workflow_dispatch:     # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv python-telegram-bot[job-queue]

      - name: Run scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          AMZN_AFFILIATE_TAG: ${{ secrets.AMZN_AFFILIATE_TAG }}
          TELEGRAM_CHANNEL:  ${{ secrets.TELEGRAM_CHANNEL }}
          DEBUG_PING:        ${{ secrets.DEBUG_PING }}
        run: |
          python scrape_and_notify.py
